### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by purewater0901** [nicklashansen/tdmpc2#6]
When I tried to run the example code, I got the following error. 

Command:
```
python train.py task=mt80 model_size=48 batch_size=1024
```

Error Message:
```
Error executing job with overrides: ['task=mt80', 'model_size=48', 'batch_size=1024']
Traceback (most recent call last):
  File "/home/yutaka/rl_project/tdmpc2/tdmpc2/train.py", line 56, in train
    trainer.train()
  File "/home/yutaka/rl_project/tdmpc2/tdmpc2/trainer/offline_trainer.py", line 47, in train
    assert self.cfg.task in self.cfg.data_dir, \
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: data_dir
    full_key: data_dir
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

All of the library should be aligned with the file in the `docker/environment.yaml`.

**Comment by VitaLemonTea1** [comment]
please open the “config.yaml” and paste the dataset path at data_dir

**Comment by purewater0901** [comment]
@VitaLemonTea1 Thank you so much!
